server:
  port: 9090

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: C:/Users/edson/IdeaProjects/unisul/ms-professor-aluno-turma/cf-server-config/arquivos-configuracao
